### ISSUE TITLE
Change of speed -> no MQtt information about it

### ISSUE THREAD

**Issue by chkbln** [toblum/McLighting#120]
Changing Speed does not generate an MQtt event.
The speed information is also not included
{"state": "ON", "color": {"r": 217, "g": 121, "b": 79}, "brightness": 59, "effect": "Single Dynamic"}
Or is that intended?

Kind regards

**Comment by debsahu** [comment]
It is intentional, there is no speed component in Home Assistant's MQTT JSON Light ( https://www.home-assistant.io/components/light.mqtt_json/ ). If you see my settings, I use a slider (input_number).

**Comment by chkbln** [comment]
Where can I find your settings?

**Comment by debsahu** [comment]
Currently it is one way, HA sends speed to McLighting. What you are looking for is McLighting send back speed to MQTT -> HA automation to read MQTT value and change HA input_slider. That can be done.

**Comment by chkbln** [comment]
I agree. You have recognized my problem. I think it makes sense that homeatomation knows the state of McLighting.
Thank you for trying to find a solution.

**Comment by debsahu** [comment]
Can you try my branch for testing ( https://github.com/debsahu/McLighting ), I confirmed it works on the McLighting side. But havent tested automation. Could you check and report back?

```
  - id: 93786598732698756967
    alias: NeoPixel Animation Speed Receive
    trigger:
    - platform: mqtt
      topic: home/McLighting01_ha/state/out
    action:
    - data:
        entity_id: input_number.neopixel_animation_speed
        value: '{{ trigger.payload | value_json.speed }}'
      service: input_number.set_value
```
