### ISSUE TITLE
Callback latency

### ISSUE THREAD

**Issue by BananaPukeh** [toblum/McLighting#267]
Hi,

I'm using this project on my MCU to power a Ledstrip from HomeAssistant. Now when I toggle the strip from HomeAssistant, it responds immediatelly. 
But HomeAssistant expects a state change callback. When it doesn't receive this within a few seconds, the UI will be reverted to the previous state. 
McLightning gives this callback, however it seems to be delayed around 5 seconds. Does anyone know if this is a "bug" or some configuration issue that can fix this?

My hass configuration:
```
- platform: mqtt_json
  name: "LED Strip"
  state_topic: "home/NodeMCU_3_ha/state/out"
  command_topic: "home/NodeMCU_3_ha/state/in"
  on_command_type: 'last'
  effect: true
  brightness: true
  color_temp: true
  rgb: true
  optimistic: false
  qos: 0
  retain: true
  effect_list: 
    - omitted
```
